var itemsId = Object.freeze({
  pneu: 1,
  Sceau: NaN,
  Metal:NaN,
  Verre:NaN,
  Papier:NaN
  Vitre:NaN,
  PaquetPapier:NaN,
  PlaqueMetal:NaN,
  SceauPneu1:NaN,
  SceauPneu2:NaN,
  SceauPneu3:NaN,
  SceauPneu0:NaN,
  SceauVerre0:NaN,
  SceauVerre1:NaN,
  SceauVerre2:NaN,
  SceauVerre3:NaN,
  SceauMetal0:NaN,
  SceauMetal1:NaN,
  SceauMetal2:NaN,
  SceauMetal3:NaN,
  SceauPlastique0:NaN,
  SceauPlastique1:NaN,
  SceauPlastique2:NaN,
  SceauPlastique3:NaN,
  BlockPlastique1:NaN,
  BlockPlastique2:NaN,
  BlockPlastique3:NaN,
  BlockMetal1:NaN,
  BlockMetal2:NaN,
  BlockMetal3:NaN,
  BlockPapier1:NaN,
  BlockPapier2:NaN,
  BlockPapier3:NaN,

  CartonPate:NaN,

});
