var itemsId = Object.freeze({
  Pneu: 1,
  Sceau: 2,
  Metal:NaN,
  Verre:NaN,
  Papier:NaN,
  Vitre:NaN,
  PaquetPapier:NaN,
  PlaqueMetal:NaN,
  SceauPneu1:NaN,
  SceauPneu2:NaN,
  SceauPneu3:NaN,
  SceauPneu0:NaN,
  SceauVerre0:NaN,
  SceauVerre1:NaN,
  SceauVerre2:NaN,
  SceauVerre3:NaN,
  SceauVerreLiquide0:NaN,
  SceauVerreLiquide1:NaN,
  SceauVerreLiquide2:NaN,
  SceauVerreLiquide3:NaN,
  SceauMetal0:3,
  SceauMetal1:4,
  SceauMetal2:5,
  SceauMetal3:6,
  SceauPlastique0:NaN,
  SceauPlastique1:NaN,
  SceauPlastique2:NaN,
  SceauPlastique3:NaN,
  BlockPlastique1:NaN,
  BlockPlastique2:NaN,
  BlockPlastique3:NaN,
  BlockMetal1:7,
  BlockMetal2:NaN,
  BlockMetal3:NaN,
  BlockPapier1:NaN,
  BlockPapier2:NaN,
  BlockPapier3:NaN,

  CartonPate:NaN,

});
